# Generated by Django 5.2.8 on 2025-11-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('published_on', models.BooleanField(default=False, verbose_name='Publié')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-last_update'],
            },
        ),
    ]
